easy_admin:
    site_name: Azobe

    design:
        menu:
            - { route: 'homepage', label: 'Retour Ã  Azobe', icon: 'home' }
            - { entity: 'User', label: 'User', icon: 'user' }
            - { entity: 'AppelProjet', label: 'AppelProjet', icon: '' }

